// This file is autogenerated by liwe3-svelte
/* eslint-disable @typescript-eslint/no-explicit-any */

/*=== f2c_start __file ===*/

/*=== f2c_end __file ===*/

/** MarkerRecord */
export interface MarkerRecord {
	/**  */
	id: string;
	/**  */
	domain: string;
	/**  */
	title: string;
	/** Marker position {lat, lng} */
	position: any;
	/**  */
	description?: string;
	/**  */
	address?: string;
	/**  */
	phone?: string;
	/** Marker email */
	email?: string;
	/** Marker website url */
	website?: string;
	/**  */
	enabled?: boolean;
}

/** Marker */
export interface Marker {
	/**  */
	id: string;
	/** Marker title */
	title: string;
	/** Marker position {lat, lng} */
	position: any;
	/** Marker full google data */
	full_address?: any[];
	/** Marker description */
	description?: string;
	/** Marker address */
	address?: string;
	/** Marker phone */
	phone?: string;
	/** Marker email */
	email?: string;
	/** Marker website url */
	website?: string;
	/**  */
	enabled?: boolean;
	/** additional data */
	extra?: any;
}

/** MarkerPosition */
export interface MarkerPosition {
	/** Marker latitude */
	lat?: number;
	/** Marker Longitude */
	lng?: number;
}

/** MarkerGoogleAddress */
export interface MarkerGoogleAddress {
	/**  */
	telephone?: string;
	/**  */
	address?: string;
	/**  */
	city?: string;
	/**  */
	postal_code?: string;
	/**  */
	province?: string;
	/**  */
	country?: string;
	/**  */
	formatted?: string;
}

